### ISSUE TITLE
Improve get channel id by name functionality

### ISSUE THREAD

**Issue by fran893** [southworks/azure-botsdk-happybirthday-bamboohr-slack-bot#10]
### Current behavior

In order to get the channel id via its name, the current bot functionality consist on execute every day the **Azure Function** in order to trigger the `api/notify` controller. When the controller is executed, the [conversation.list](https://api.slack.com/methods/conversations.list) method from the **Slack API** is executed it, so in each execution the method is called.

The **Slack channel name** is configured in the `appsettings.json file`.

### Expected behavior

The expected functionality is that the bot be able to get the channel id in its beginning and store it in some place, consult it every time that the **Azure Function** is executed  and avoid call the **Slack API** every time.

**Possible locations to store the channel id**

- [ ] Azure Blob Storage

**Comment by nelsonsouthworks** [comment]
closed this in #27
