### ISSUE TITLE
[Bug] Parameters Missing in AZ Function

### ISSUE THREAD

**Issue by fran893** [southworks/azure-botsdk-happybirthday-bamboohr-slack-bot#29]
**Describe the bug**

When the **Azure Function** is published and not all the **parameters** specified in the `local.settings.json` file are **created** in the **Application Settings** Section, the function **throws** an error and is not executed

**To Reproduce**

Publish the [Azure Function](https://github.com/southworks/azure-botsdk-happybirthday-bot/tree/azure-functions/bamboohrapi/azure-functions/DataIngestionBambooAPI) of this repository, after published delete a parameter from the Application Settings section and then execute it. Or before publish it, don't configure at least one of the parameter specified in the local.settings.json file, then publish it and execute it.

**Expected behavior**

The function must be executed even if parameters are missing (not created)

**Environment information**
 - OS: Windows 10 Pro x64 
 - Browser: Microsoft Edge
 - Version: 84.0.522.63

**Comment by nelsonsouthworks** [comment]
Hi @fran893 , thanks for your observation. I tell you that it is okay for it to fail if it does not have any of those values because they are essential, and if they are not there, there is no value that can be defaulted.

**Comment by nelsonsouthworks** [comment]
Hi @fran893 , thanks for your observation. I tell you that it is okay for it to fail if it does not have any of those values because they are essential, and if they are not there, there is no value that can be defaulted.
