### ISSUE TITLE
Templates for different kinds of issues

### ISSUE THREAD

**Issue by gonzalomleon** [southworks/azure-botsdk-happybirthday-bamboohr-slack-bot#6]
## Description
It could be nice to have templates for different kind of issues, like:
- bug_report
- docs-bug-report
- feature_request
- question

### As an example: 
**Templates**
- https://github.com/microsoft/botframework-solutions/tree/master/.github/ISSUE_TEMPLATE

**How it works**
- https://github.com/microsoft/botframework-solutions/issues/new/choose

**Comment by nelsonsouthworks** [comment]
closed this in #14
